"""Make relationship one-to-one

Revision ID: 3308cb23962b
Revises: f08a57274b5c
Create Date: 2025-05-28 13:50:29.181171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3308cb23962b"
down_revision: Union[str, None] = "f08a57274b5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "message_reviews", ["message_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message_reviews", type_="unique")
    # ### end Alembic commands ###
