"""Change db structure

Revision ID: 68334e9a748c
Revises: 311cd866f953
Create Date: 2025-06-05 11:18:50.693772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68334e9a748c"
down_revision: Union[str, None] = "311cd866f953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_feedbacks",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("like_status", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', now())"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["bot_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "message_id"),
    )
    op.add_column(
        "bot_messages", sa.Column("model_used", sa.String(), nullable=True)
    )
    op.add_column(
        "bot_messages", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("uq_llm_text_user_question"), "bot_messages", type_="unique"
    )
    op.create_foreign_key(
        None, "bot_messages", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bot_messages", type_="foreignkey")
    op.create_unique_constraint(
        op.f("uq_llm_text_user_question"),
        "bot_messages",
        ["llm_text", "user_question"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("bot_messages", "user_id")
    op.drop_column("bot_messages", "model_used")
    op.drop_table("message_feedbacks")
    # ### end Alembic commands ###
