"""Add translated_user_question

Revision ID: de5d672ff124
Revises: 1f91b2dd9fa1
Create Date: 2025-05-28 15:10:04.749071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de5d672ff124"
down_revision: Union[str, None] = "1f91b2dd9fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_messages",
        sa.Column("translated_user_question", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_messages", "translated_user_question")
    # ### end Alembic commands ###
