"""Add timestamp

Revision ID: 0126a6626686
Revises: de5d672ff124
Create Date: 2025-05-30 09:30:09.555615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0126a6626686"
down_revision: Union[str, None] = "de5d672ff124"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_messages",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('UTC', now())"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_messages", "timestamp")
    # ### end Alembic commands ###
