services:
  api:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mistral
    networks:
      - app-network

  mistral:
    build:
      dockerfile: Dockerfile-ollama
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=${LLM__HOST}
      - OLLAMA_MODEL=${LLM__MODEL}
    ports:
      - "${LLM__PORT}:11434"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
