services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network

#  mistral:
#    image: ollama/ollama:latest
#    env_file:
#      - .env
#    environment:
#      - OLLAMA_HOST=${LLM__HOST}
#      - OLLAMA_MODEL=${LLM__MODEL}
#    ports:
#      - "${LLM__PORT}:${LLM__PORT}"
#    restart: always
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
